# Generated by Django 6.0.1 on 2026-02-01 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracking", "0001_initial"),
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="workout_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs",
                to="workouts.workoutdaytemplate",
            ),
        ),
        migrations.AddField(
            model_name="setlog",
            name="workout_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_logs",
                to="tracking.workoutlog",
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["user", "date"], name="workout_log_user_id_e8e75a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["user", "completed"], name="workout_log_user_id_5686d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workoutlog",
            unique_together={("user", "workout_day", "date")},
        ),
        migrations.AddIndex(
            model_name="setlog",
            index=models.Index(
                fields=["workout_log", "exercise"], name="set_logs_workout_e4c677_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="setlog",
            unique_together={("workout_log", "exercise", "set_number")},
        ),
    ]
