# Generated by Django 6.0.1 on 2026-02-11 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
        ("exercises", "0001_initial"),
        ("tracking", "0002_initial"),
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setlog",
            options={"ordering": ["set_number"]},
        ),
        migrations.AlterModelOptions(
            name="workoutlog",
            options={"ordering": ["-date", "day_order"]},
        ),
        migrations.RemoveIndex(
            model_name="setlog",
            name="set_logs_workout_e4c677_idx",
        ),
        migrations.RemoveIndex(
            model_name="workoutlog",
            name="workout_log_user_id_e8e75a_idx",
        ),
        migrations.RemoveIndex(
            model_name="workoutlog",
            name="workout_log_user_id_5686d8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="setlog",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workoutlog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="setlog",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="day_order",
            field=models.IntegerField(
                default=1, help_text="Posición del día en la semana (1, 2, 3, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="week_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignación de semana a la que pertenece este log",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_logs",
                to="assignments.userweekassignment",
            ),
        ),
        migrations.AlterField(
            model_name="setlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="setlog",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exercises.exercise"
            ),
        ),
        migrations.AlterField(
            model_name="setlog",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="setlog",
            name="reps",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="setlog",
            name="set_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="setlog",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="completed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="workout_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="workouts.workoutdaytemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workoutlog",
            unique_together={("user", "workout_day", "day_order", "date")},
        ),
    ]
