# Generated by Django 6.0.1 on 2026-02-01 02:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutDayTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LEG_DAY", "Leg Day"),
                            ("UPPER_BODY_DAY", "Upper Body Day"),
                            ("PULL_DAY", "Pull Day"),
                            ("PUSH_DAY", "Push Day"),
                            ("FULL_BODY_DAY", "Full Body Day"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "workout_day_templates",
                "ordering": ["type"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutWeekTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "workout_week_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutDayExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "number_of_sets",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workout_days",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.workoutdaytemplate",
                    ),
                ),
            ],
            options={
                "db_table": "workout_day_exercises",
                "ordering": ["workout_day", "order"],
                "indexes": [
                    models.Index(
                        fields=["workout_day", "order"],
                        name="workout_day_workout_32335e_idx",
                    )
                ],
                "unique_together": {("workout_day", "exercise")},
            },
        ),
        migrations.CreateModel(
            name="WorkoutWeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "day_order",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="week_days",
                        to="workouts.workoutdaytemplate",
                    ),
                ),
                (
                    "week_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="workouts.workoutweektemplate",
                    ),
                ),
            ],
            options={
                "db_table": "workout_week_days",
                "ordering": ["week_template", "day_order"],
                "indexes": [
                    models.Index(
                        fields=["week_template", "day_order"],
                        name="workout_wee_week_te_785ba5_idx",
                    )
                ],
                "unique_together": {("week_template", "day_order")},
            },
        ),
    ]
