# Generated by Django 6.0.1 on 2026-02-11 20:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCustomExerciseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "number_of_sets",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_exercise_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_day_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_customizations",
                        to="workouts.workoutdayexercise",
                    ),
                ),
            ],
            options={
                "db_table": "user_custom_exercise_configs",
                "indexes": [
                    models.Index(
                        fields=["user", "workout_day_exercise"],
                        name="user_custom_user_id_b97fea_idx",
                    )
                ],
                "unique_together": {("user", "workout_day_exercise")},
            },
        ),
        migrations.CreateModel(
            name="UserCustomWorkoutDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "day_order",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_workout_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_customizations",
                        to="workouts.workoutdaytemplate",
                    ),
                ),
            ],
            options={
                "db_table": "user_custom_workout_days",
                "ordering": ["user", "day_order"],
                "indexes": [
                    models.Index(
                        fields=["user", "day_order"],
                        name="user_custom_user_id_0c2cab_idx",
                    )
                ],
                "unique_together": {("user", "day_order")},
            },
        ),
        migrations.CreateModel(
            name="UserWeekAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("start_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "week_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_assignments",
                        to="workouts.workoutweektemplate",
                    ),
                ),
            ],
            options={
                "db_table": "user_week_assignments",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_week_a_user_id_eaa3b0_idx",
                    ),
                    models.Index(
                        fields=["user", "start_date"],
                        name="user_week_a_user_id_d9d734_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "week_template", "start_date"),
                        name="unique_user_week_start",
                    )
                ],
            },
        ),
    ]
