# Generated by Django 6.0.1 on 2026-02-01 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustomexerciseconfig",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_exercise_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercustomexerciseconfig",
            name="workout_day_exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_customizations",
                to="workouts.workoutdayexercise",
            ),
        ),
        migrations.AddField(
            model_name="usercustomworkoutday",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_workout_days",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercustomworkoutday",
            name="workout_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_customizations",
                to="workouts.workoutdaytemplate",
            ),
        ),
        migrations.AddField(
            model_name="userweekassignment",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="week_assignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userweekassignment",
            name="week_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_assignments",
                to="workouts.workoutweektemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="usercustomexerciseconfig",
            index=models.Index(
                fields=["user", "workout_day_exercise"],
                name="user_custom_user_id_b97fea_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercustomexerciseconfig",
            unique_together={("user", "workout_day_exercise")},
        ),
        migrations.AddIndex(
            model_name="usercustomworkoutday",
            index=models.Index(
                fields=["user", "day_order"], name="user_custom_user_id_0c2cab_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercustomworkoutday",
            unique_together={("user", "day_order")},
        ),
        migrations.AddIndex(
            model_name="userweekassignment",
            index=models.Index(
                fields=["user", "is_active"], name="user_week_a_user_id_eaa3b0_idx"
            ),
        ),
    ]
