# Generated by Django 6.0.1 on 2026-02-01 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("QUADRICEPS", "Quadriceps"),
                            ("HAMSTRINGS", "Hamstrings"),
                            ("GLUTES", "Glutes"),
                            ("CALVES", "Calves"),
                            ("LATS", "Lats"),
                            ("TRAPS", "Traps"),
                            ("LOWER_BACK", "Lower Back"),
                            ("CHEST", "Chest"),
                            ("FRONT_DELTS", "Front Deltoids"),
                            ("SIDE_DELTS", "Side Deltoids"),
                            ("REAR_DELTS", "Rear Deltoids"),
                            ("BICEPS", "Biceps"),
                            ("TRICEPS", "Triceps"),
                            ("FOREARMS", "Forearms"),
                            ("ABS", "Abs"),
                            ("OBLIQUES", "Obliques"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "exercises",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["muscle_group", "is_active"],
                        name="exercises_muscle__e19804_idx",
                    )
                ],
            },
        ),
    ]
